FROM ubuntu:focal

ARG BUNDLE_DIR

RUN apt-get update && apt-get install -y ca-certificates curl unzip libicu66
RUN curl -L -O https://github.com/Azure/kubelogin/releases/download/v0.0.13/kubelogin-linux-amd64.zip
RUN unzip kubelogin-linux-amd64.zip
RUN mv ./bin/linux_amd64/kubelogin /usr/bin/ && \
    chmod a+x /usr/bin/kubelogin

# This is a template Dockerfile for the bundle's invocation image
# You can customize it to use different base images, install tools and copy configuration files.
#
# Porter will use it as a template and append lines to it for the mixins
# and to set the CMD appropriately for the CNAB specification.
#
# Add the following line to porter.yaml to instruct Porter to use this template
# dockerfile: Dockerfile.tmpl

# You can control where the mixin's Dockerfile lines are inserted into this file by moving "# PORTER_MIXINS" line
# another location in this file. If you remove that line, the mixins generated content is appended to this file.
# PORTER_MIXINS

# Use the BUNDLE_DIR build argument to copy files into the bundle
COPY . $BUNDLE_DIR